function process_spk_file(spk_paths, output_path)
    %% process_spk_file(spk_paths, output_path)
    %
    % processes one or more 

    if ~exist('output_path', 'var')
        [spk_dir, spk_name] = fileparts(spk_paths{1});
        output_path = fullfile(spk_dir, [spk_name, '.mat']);
        disp(['Output path not specified! Saving to ', output_path])
    end

    axis_loader = AxisLoader(spk_paths);
    output_file = matfile(output_path, 'Writable', true);
    cell_shape = axis_loader.get_cell_shape();
    feat_cell = cell(cell_shape);
    model_cell = cell(cell_shape);
    clust_cell = cell(cell_shape);
    % This is how you have to preallocate object containers in matlab
    output_file.electrode_containers = cell(cell_shape);

    for i = 1:axis_loader.num_channels
        [spike_data, channel] = axis_loader.load_next_data_set();
        disp(['Num Spikes: ', num2str(length(spike_data))])
        if length(spike_data) > 20 % Feature Extraction requires at least three spikes
            features = get_spike_features(spike_data);
            models = fit_models_to_features(features, 'pca');
            clusters = cellfun(@(m) m.cluster(features.pc_scores), models, 'UniformOutput', false);
            feat_cell{i} = features;
            model_cell{i} = models;
            clust_cell{i} = clusters;
            output_file.electrode_containers( ...
                channel.WellRow, ...
                channel.WellColumn, ...
                channel.ElectrodeColumn, ...
                channel.ElectrodeRow ...
                ) = {cells_to_container( ...
                spike_data, ...
                features, ...
                models, ...
                clusters ...
            )};
        else
            output_file.electrode_containers( ...
                channel.WellRow, ...
                channel.WellColumn, ...
                channel.ElectrodeColumn, ...
                channel.ElectrodeRow ...
                ) = {ElectrodeContainer()};
        end
    end


function datasets = load_axis_datasets(filepaths)
    datasets = cell(size(filepaths));
    for i = 1:numel(filepaths)
        datasets{i} = AxisFile(filepaths{i}).DataSets.LoadData();
    end

function container = cells_to_container(spikes, feat_struct, model, cluster_array)
    if length(spikes) > 20 % This is the minimum number of spikes that are processed in main
        spike_mat = horzcat(spikes(:).GetVoltageVector())';
        spike_times = spike_times_to_datetime( ...
            spikes(1).Source.Header.FileStartTime, ...
            [spikes(:).Start] ...
        );
        valid = true(size(cluster_array));
        contains_data = true;
    else
        spike_mat = [];
        spike_times = [];
        valid = false;
        contains_data = false;
    end

    container = ElectrodeContainer( ...
        spike_mat,                  ...
        spike_times,                ...
        'valid', valid,             ...
        'class_no', cluster_array,  ...
        'features', feat_struct,    ...
        'cluster_model', model,     ...
        'contains_data', contains_data ...
    );

function dts = spike_times_to_datetime(fst, spike_starts)
    %% dts = spike_times_to_datetime(file_start_time, spike_starts)
    %
    % 
    for i = 1:length(spike_starts)
        dts(i) = datetime( ...
            fst.Year, ...
            fst.Month, ...
            fst.Day, ...
            fst.Hour, ...
            fst.Minute, ...
            fst.Second + spike_starts(i) ...
        );
    end
